### ISSUE TITLE
Abe crash when changing reference file

### ISSUE THREAD

**Issue by wonknu** [abecms/abecms#225]
To reproduce the bug

1) open a json reference file
2) add new line at the end of the file for example
3) save the file

result: it makes abe quit with this output
```
TypeError: Cannot read property 'emit' of undefined
    at EventEmitter.<anonymous> (/PATH/USER/GLOBAL/NODE_MODULES/node_modules/abecms/dist/cli/core/manager/Manager.js:262:36)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at /PATH/USER/GLOBAL/NODE_MODULES/node_modules/abecms/node_modules/watch/main.js:155:22
    at StatWatcher.<anonymous> (/PATH/USER/GLOBAL/NODE_MODULES/node_modules/abecms/node_modules/watch/main.js:83:38)
    at emitTwo (events.js:106:13)
    at StatWatcher.emit (events.js:191:7)
    at StatWatcher._handle.onchange (fs.js:1501:10)

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

**Comment by gregorybesson** [comment]
fixed in 3.4.0 version
