### ISSUE TITLE
Uploading an image make abe crash

### ISSUE THREAD

**Issue by vincentdesmares** [abecms/abecms#251]
I'm trying to upload an image called "teamstarterrectangle 5.png" with this tag:

`{abe type='image' key='feature-1-image' desc='Image' width='273' height='154' alt='' tab='feature1'}}`

When I do, abe crash with this error:

```
Manager updated
/Users/vincent/.nvm/versions/node/v7.7.2/lib/node_modules/abecms/dist/server/app.js:185
      throw err;
      ^

RangeError: out of range index
    at Object.filterNone (/Users/vincent/.nvm/versions/node/v7.7.2/lib/node_modules/abecms/node_modules/pngjs/lib/filter-pack.js:6:10)
    at module.exports (/Users/vincent/.nvm/versions/node/v7.7.2/lib/node_modules/abecms/node_modules/pngjs/lib/filter-pack.js:180:17)
    at module.exports.Packer.filterData (/Users/vincent/.nvm/versions/node/v7.7.2/lib/node_modules/abecms/node_modules/pngjs/lib/packer.js:61:22)
    at module.exports.PackerAsync.pack (/Users/vincent/.nvm/versions/node/v7.7.2/lib/node_modules/abecms/node_modules/pngjs/lib/packer-async.js:30:35)
    at exports.PNG.<anonymous> (/Users/vincent/.nvm/versions/node/v7.7.2/lib/node_modules/abecms/node_modules/pngjs/lib/png.js:59:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
Here is the image url, in case it could help : https://teamstarter.co/img/teamstarterrectangle%205.png

**Comment by gregorybesson** [comment]
thx @vincentdesmares I think the bug is related to the %20.

Let me fix this

**Comment by gregorybesson** [comment]
This is not related to the name of the image. This image is uploaded on my node 7.8 version. 
Let me dig in

**Comment by vincentdesmares** [comment]
The problem is solved! Thank you very much for fixing it so quickly!
