### ISSUE TITLE
ReferenceError: Manager is not defined, when trying to preview Abe Demo using abecms@3.6.10

### ISSUE THREAD

**Issue by vaughanwatson** [abecms/abecms#253]
**ReferenceError: Manager is not defined**, when trying to preview Abe Demo using abecms@3.6.10 http://localhost:3000/abe/editor/articles/article-1.html

I'm new to Abe CMS and tried to play with the demo over the weekend but got this error. Not sure what I did wrong or if I should post this issue under [https://github.com/abecms/demo/issues](https://github.com/abecms/demo/issues)

**ReferenceError: Manager is not defined**
    at middleware (E:\nodejs\node_modules\abecms\dist\server\middlewares\website.js:29:36)
    at Layer.handle [as handle_request] (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:317:13)
    at E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:284:7
    at next (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:275:10)
    at middleware (E:\nodejs\node_modules\abecms\dist\server\middlewares\login.js:26:5)
    at Layer.handle [as handle_request] (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:317:13)
    at E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:284:7
    at next (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:275:10)
    at middleware (E:\nodejs\node_modules\abecms\dist\server\middlewares\isAuthorized.js:16:7)
    at Layer.handle [as handle_request] (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:317:13)
    at E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:284:7
    at next (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:275:10)
    at trim_prefix (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:317:13)
    at E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:284:7
    at next (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (E:\nodejs\node_modules\abecms\node_modules\body-parser\lib\types\json.js:109:7)
    at Layer.handle [as handle_request] (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:317:13)
    at E:\nodejs\node_modules\abecms\node_modules\express\lib\router\index.js:284:7

**Comment by gregorybesson** [comment]
Hello @vaughanwatson 
It has been fixed in the version 3.7.*

Come join us on abecms Slack: send me a mail at greg@abecms.com, I'll send you an invite :)
