### ISSUE TITLE
'abe-mailer' is not in the npm registry

### ISSUE THREAD

**Issue by vaughanwatson** [abecms/abecms#254]
**'abe-mailer' is not in the npm registry**.

0 info it worked if it ends with ok
1 verbose cli [ 'E:\\nodejs\\node.exe',
1 verbose cli   'E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'abe-mailer',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData abe-mailer
8 silly fetchNamedPackageData abe-mailer
9 silly mapToRegistry name abe-mailer
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'abe-mailer',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'abe-mailer',
12 silly mapToRegistry   name: 'abe-mailer',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/abe-mailer
14 verbose request uri https://registry.npmjs.org/abe-mailer
15 verbose request no auth needed
16 info attempt registry request try #1 at 7:37:57 PM
17 verbose request id c384330e07c8bac5
18 http request GET https://registry.npmjs.org/abe-mailer
19 http 404 https://registry.npmjs.org/abe-mailer
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Mon, 23 Oct 2017 18:38:13 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lhr6333-LHR',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1508783893.427402,VS0,VE386',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Mon, 23 Oct 2017 18:38:13 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lhr6333-LHR',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1508783893.427402,VS0,VE386',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/abe-mailer
22 silly fetchPackageMetaData     at makeError (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (E:\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (E:\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (E:\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
22 silly fetchPackageMetaData  error for abe-mailer { Error: Registry returned 404 for GET on https://registry.npmjs.org/abe-mailer
22 silly fetchPackageMetaData     at makeError (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (E:\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (E:\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (E:\nodejs\node_modules\npm\node_modules\request\request.js:969:12) pkgid: 'abe-mailer', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/abe-mailer
27 verbose stack     at makeError (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
27 verbose stack     at Request._callback (E:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
27 verbose stack     at Request.self.callback (E:\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
27 verbose stack     at emitTwo (events.js:106:13)
27 verbose stack     at Request.emit (events.js:191:7)
27 verbose stack     at Request.<anonymous> (E:\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
27 verbose stack     at emitOne (events.js:96:13)
27 verbose stack     at Request.emit (events.js:188:7)
27 verbose stack     at IncomingMessage.<anonymous> (E:\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
28 verbose statusCode 404
29 verbose pkgid abe-mailer
30 verbose cwd E:\projects\blog
31 error Windows_NT 6.1.7601
32 error argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "abe-mailer" "--save"
33 error node v6.11.3
34 error npm  v3.10.10
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/abe-mailer
37 error 404
38 error 404 'abe-mailer' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]

**Comment by gregorybesson** [comment]
hello @vaughanwatson : How did you obtain this error ?

can you describe the process ?

Thx !
Greg

**Comment by vaughanwatson** [comment]
Hi @gregorybesson: error occurs when you type from the command line npm i --save abe-mailer
