### ISSUE TITLE
Abecms fails to install on macOS HIgh Sierra

### ISSUE THREAD

**Issue by yacc** [abecms/abecms#276]
Can't install the cms on MacOS High Sierra with the following conf:
```~/Development/Blog
➜ node -v
v9.10.1
~/Development/Blog
➜ npm -v
5.8.0
```
This is the error I'm getting:
```
➜ npm install -g abecms
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated natives@1.1.2: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated sendgrid@1.9.2: Please see v6.X+ at https://www.npmjs.com/org/sendgrid
npm WARN deprecated tar.gz@0.1.1: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/abe -> /usr/local/lib/node_modules/abecms/dist/index.js

> opencv@5.0.0 install /usr/local/lib/node_modules/abecms/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/Cellar/node/9.10.1/bin/node',
node-pre-gyp verb cli   '/usr/local/lib/node_modules/abecms/node_modules/opencv/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.17
node-pre-gyp info using node@9.10.1 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/usr/local/lib/node_modules/abecms/node_modules/opencv/build/opencv/v5.0.0/Release/node-v59-darwin-x64/opencv.node" (not found)
node-pre-gyp http GET https://node-opencv.s3.amazonaws.com/opencv/v5.0.0/Release/node-v59-darwin-x64.tar.gz
node-pre-gyp http 403 https://node-opencv.s3.amazonaws.com/opencv/v5.0.0/Release/node-v59-darwin-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://node-opencv.s3.amazonaws.com/opencv/v5.0.0/Release/node-v59-darwin-x64.tar.gz (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]
/usr/local/lib/node_modules/abecms/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /usr/local/lib/node_modules/abecms/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:280:5)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/Cellar/node/9.10.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/abecms/node_modules/opencv/build/opencv/v5.0.0/Release/node-v59-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/usr/local/lib/node_modules/abecms/node_modules/opencv/build/opencv/v5.0.0/Release/node-v59-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/abecms/node_modules/opencv
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/9.10.1/bin/node /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/abecms/node_modules/opencv/build/opencv/v5.0.0/Release/node-v59-darwin-x64/opencv.node --module_name=opencv --module_path=/usr/local/lib/node_modules/abecms/node_modules/opencv/build/opencv/v5.0.0/Release/node-v59-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/abecms/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/9.10.1/bin/node" "/usr/local/lib/node_modules/abecms/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/abecms/node_modules/opencv
node-pre-gyp ERR! node -v v9.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/9.10.1/bin/node /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/abecms/node_modules/opencv/build/opencv/v5.0.0/Release/node-v59-darwin-x64/opencv.node --module_name=opencv --module_path=/usr/local/lib/node_modules/abecms/node_modules/opencv/build/opencv/v5.0.0/Release/node-v59-darwin-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: opencv@5.0.0 (node_modules/abecms/node_modules/opencv):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ abecms@3.7.5
updated 1 package in 15.918s
```

**Comment by gregorybesson** [comment]
hello @yacc Abe installation is correct. This is the optional module OpenCV (used for AI) that doesn't.
In the next major version of AbeCMS, it will be removed from the core and will become a plugin.
