### ISSUE TITLE
[BUG]: Abe CLI fails on init

### ISSUE THREAD

**Issue by ddorstijn** [abecms/abecms#285]
AbeCMS version: 5.10.2
NodeJS version: 18.2.0
OS: Windows

Currently running `abe init` results in an error. It seems like the inquirer package is no longer a CommonJS module, resulting in the following error:

``` bash
var _inquirer = _interopRequireDefault(require("inquirer"));
                                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module inquirer@9.1.4\node_modules\inquirer\lib\inquirer.js from abecms@5.10.2\node_modules\abecms\dist\cli\cms\operations\initSite.js not supported.
Instead change the require of inquirer.js in abecms@5.10.2\node_modules\abecms\dist\cli\cms\operations\initSite.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (abecms@5.10.2\node_modules\abecms\dist\cli\cms\operations\initSite.js:24:40)
    at Object.<anonymous> (abecms@5.10.2\node_modules\abecms\dist\cli\cms\operations\index.js:54:40)
    at Object.<anonymous> (abecms@5.10.2\node_modules\abecms\dist\index.js:6:19) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by Axellarator** [comment]
ABE seems to be dead. Same error today 09.2023

**Comment by 7ognivo** [comment]
The inquirer package, as of version 9 and higher, is a native ECMAScript module (ESM). 
From [Inquirer npm page](https://www.npmjs.com/package/inquirer).

`npm install --save inquirer@^8.0.0`
This will then allow import inquirer with the commonjs require:

`const inquirer = require('inquirer');`

Tried to do that using npm-shrinkwrap.json. It actually worked. 

But then I encountered several more instances of the same error for chalk, figures...

Same solution did not help with 'figures'.. Don't really have that much time to experiment further.

**Comment by 7ognivo** [comment]
And yeah.. Too bad it's dead.
It's actually just the right tool I need right now, but it's way outdated.
In case you know of working self-hosted alternatives, pls, drop a link
